// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhzlTYcmDT7HfWDknmoXK30ffKN8N-E3A',
    appId: '1:856140989408:web:fb96c5f6f266107bdd2185',
    messagingSenderId: '856140989408',
    projectId: 'rupiya-finnovation-practical',
    authDomain: 'rupiya-finnovation-practical.firebaseapp.com',
    storageBucket: 'rupiya-finnovation-practical.appspot.com',
    measurementId: 'G-0GHJY2PKHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSVlDq27CjL-qDIXcBmgcKhaiho-zDt6U',
    appId: '1:856140989408:android:f6ab7768e5008058dd2185',
    messagingSenderId: '856140989408',
    projectId: 'rupiya-finnovation-practical',
    storageBucket: 'rupiya-finnovation-practical.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB28l151pDeEDoIoSXTS1dwwBZHcmd0UrE',
    appId: '1:856140989408:ios:3bd65c980d1525dadd2185',
    messagingSenderId: '856140989408',
    projectId: 'rupiya-finnovation-practical',
    storageBucket: 'rupiya-finnovation-practical.appspot.com',
    iosBundleId: 'com.example.rupiyaFinnovationsPracticalTestKinjalrathod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB28l151pDeEDoIoSXTS1dwwBZHcmd0UrE',
    appId: '1:856140989408:ios:d2f00223df01f08bdd2185',
    messagingSenderId: '856140989408',
    projectId: 'rupiya-finnovation-practical',
    storageBucket: 'rupiya-finnovation-practical.appspot.com',
    iosBundleId: 'com.example.rupiyaFinnovationsPracticalTestKinjalrathod.RunnerTests',
  );
}
